name: Type checking

on:
  push:
    branches: [ master, develop]
  pull_request:
    branches: [ master, develop]

jobs:
  code:
    name: Type checking code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run TypeScript
        run: yarn tsc
